feature: custom templates / download default template
jonjampen/obsidian-xournalpp pull request #1
Opened 2024-07-12 20:58 UTC by KiraGreifeneder

Fixes issue where the template file wasn't downloaded during installation from the community plugins tab. Solved by downloading it from the repo on note creation when necessary.

Adds the ability for users to define a custom template.

- Added settings field that allows user to specify a path to a custom template
- Added functions in xoppActions.ts to get user template path if it is set or the default template
  - Added a util function in downloader.ts

This is my first PR on a repo like this so let me know if anything is weird or changes need to be made 😅 greetings from Austria

2024-07-16 09:19 UTC, jonjampen requested changes
Thank you for your contribution!

Please use indentation with spaces (4 spaces per indentation level) instead of tabs for consistency.

2024-07-16 09:19 UTC, jonjampen commented on src/downloader.ts
According to the Obsidian Developer Policies, a plugin is not allowed to download files over the network:

> Themes may not load assets from the network. [Obsidian Developer Policies](https://docs.obsidian.md/Developer+policies#Not+allowed)

I think we have to include the template in the code (as the file is quite small, that should not be an issue). The steps would probably be:

1. Convert .xopp template to base64 and store that as a string in a js file
2. Import the base64 string from the file into a `createTemplate()` function
3. This function converts the base64 to an arrayBuffer and then creates a file in the file system using the [createBinary method](https://docs.obsidian.md/Reference/TypeScript+API/Vault/createBinary#Vault.createBinary()+method)

Or do you have another idea?

Would you be able to implement those changes? Thank you for your contribution!

2024-07-16 09:22 UTC, jonjampen commented
Thank you for developing the custom template feature, that is great!

2024-07-16 12:00 UTC, KiraGreifeneder commented on src/downloader.ts
Oh wow thank you so much for looking into that, I didn't realize that could be an issue. Keeping it in the code is a much better idea, I'll work on it sometime this week, along with fixing the indentation.

Thanks for taking the time!

2024-07-16 14:52 UTC, jonjampen commented on src/downloader.ts
That's awesome, thank you!

2024-07-17 21:03 UTC, KiraGreifeneder commented
Hi, I implemented your requested changes.

Btw, I later noticed that the Obsidian guidelines only say that _themes_ can't download assets, so I think plugins are allowed to.
I think your approach is still better though, so I stuck to your recommendation.

- stored the template as a base64 string in template.ts
- replaced downloadTemplate() with a createTemplate() function that converts the string to an ArrayBuffer and creates the template file from it

2024-07-18 11:07 UTC, jonjampen approved these changes
Thank you so much for taking the time to improve the plugin!
Your changes look great, I will merge it and create a new patch release.

2024-07-18 11:08 UTC, jonjampen commented
> Btw, I later noticed that the Obsidian guidelines only say that _themes_ can't download assets, so I think plugins are allowed to. I think your approach is still better though, so I stuck to your recommendation.

You are right! But I agree, that it is still better to keep the plugin running offline 👍.

2024-07-18 11:13 UTC, merged

2024-07-18 21:22 UTC, KiraGreifeneder commented
thanks so much for your patience and reviews!